Repository frankwon11/PickPack, pull requests merged in 2024-08, with the labels that each got.

#8 [Design] #5 - 메인 화면 레이아웃 작성
  PickPack.xcodeproj/project.pbxproj
  PickPack/View/CarouselView.swift
  PickPack/View/EmptyTicketView.swift
  PickPack/View/MainView.swift
  PickPack/View/TicketView.swift
Labels: 🦊슌

#11 [Feat] #11 - AppleLogin 화면 및 기능 구현
  PickPack.xcodeproj/project.pbxproj
  PickPack/Helper/KeychainHelper.swift
  PickPack/Manager/AppleAuthManager.swift
  PickPack/PickPack.entitlements
  PickPack/PickPackApp.swift
  PickPack/View/AppleLoginView.swift
  PickPack/View/ContentView.swift
  PickPack/View/MainView.swift
Labels: 🐻앤드류

#12 [Setting] #9 - Color Asset 뷰에 반영
  PickPack.xcodeproj/project.pbxproj
  PickPack.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PickPack/View/EmptyTicketView.swift
  PickPack/View/TicketView.swift
Labels: 🦊슌

#18 [Design] #17 - 짐 추가 뷰 레이아웃 작성
  PickPack.xcodeproj/project.pbxproj
  PickPack/Models/Item.swift
  PickPack/Models/ItemList.swift
  PickPack/Views/AddItemSheet.swift
  PickPack/Views/MainView.swift
Labels: 🦊슌

#21 [Design/#7] - RoomView 상단 구현
  PickPack.xcodeproj/project.pbxproj
  PickPack/Views/Room/RoomView.swift
  PickPack/Views/Room/RoomViewTabs.swift
Labels: 🍔맥

#26 [Feat] #23 - 데이터 모델 생성
  PickPack.xcodeproj/project.pbxproj
  PickPack/Models/CustomColor.swift
  PickPack/Models/Item.swift
  PickPack/Models/Member.swift
  PickPack/Models/Room.swift
  PickPack/Models/SharedItem.swift
  PickPack/Models/User.swift
Labels: 🐻앤드류

#39 [Design] #35 - AddItemSheet 스타일 적용
  PickPack.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PickPack/Views/AddItemSheet.swift
  PickPack/Views/Room/MyItem/MyItemView.swift
Labels: 🍔맥

#41 [Design] #37 - HistoryView 레이아웃 작성
  PickPack.xcodeproj/project.pbxproj
  PickPack/Managers/RouterManager.swift
  PickPack/Views/History/HistoryView.swift
  PickPack/Views/Main/MainView.swift
Labels: 🦊슌

#45 [Chore] #43 - Auth 및 User 생성 재구현
  PickPack.xcodeproj/project.pbxproj
  PickPack.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PickPack/App/PickPackApp.swift
  PickPack/Managers/AppleAuthManager.swift
  PickPack/Managers/FirestoreManager.swift
  PickPack/Views/FirebaseLoginTest.swift
  PickPack/Views/Login/AppleLoginView.swift
Labels: 🐻앤드류

#47 [Design] #46 - FriendItem 추가
  PickPack.xcodeproj/project.pbxproj
  PickPack/Views/Room/FriendItem/FriendItemList.swift
  PickPack/Views/Room/FriendItem/FriendItemListView.swift
  PickPack/Views/Room/FriendItem/FriendItemRowView.swift
  PickPack/Views/Room/FriendItem/FriendItemView.swift
  PickPack/Views/Room/FriendItem/FriendRow.swift
  PickPack/Views/Room/FriendItem/FriendSharedList.swift
Labels: 🐻앤드류

#50 [Feat] #42 - Date Extension 구현
  PickPack.xcodeproj/project.pbxproj
  PickPack/App/PickPackApp.swift
  PickPack/Helpers/Date+Extension.swift
  PickPack/Views/History/HistoryView.swift
Labels: 🦊슌

#52 [Design] #51 - 세이디 파이팅
  PickPack.xcodeproj/project.pbxproj
  PickPack/Managers/RouterManager.swift
  PickPack/Views/CreateRoom/CreateRoomView.swift
  PickPack/Views/CreateRoom/ReadyRoomView.swift
  PickPack/Views/Main/MainView.swift
  PickPack/Views/Room/RoomView.swift
  PickPack/Views/Room/SharedItem/ShareItemDoneList.swift
  PickPack/Views/Room/SharedItem/SharedItemNotYet.swift
  PickPack/Views/Room/SharedItem/SharedItemNotYetList.swift
  PickPack/Views/Room/SharedItem/SharedItemView.swift
  PickPack/Views/Setting/FAQView.swift
  PickPack/Views/Setting/RoomSettingView.swift
  PickPack/Views/Setting/SettingDestinationView.swift
  PickPack/Views/Setting/SettingDurationField.swift
  PickPack/Views/Setting/SettingRoomColorField.swift
  PickPack/Views/Setting/SettingRoomNameField.swift
  PickPack/Views/Setting/SettingView.swift
Labels: 🐹세이디, 🦊슌

#58 [Design] #56 - 사용자정의 짐 화면 레이아웃 구현
  PickPack.xcodeproj/project.pbxproj
  PickPack/Views/AddItemSheet.swift
  PickPack/Views/CustomItemAddView.swift
Labels: 🍔맥

#60 [Feat] #48 - FirestoreManager 기능 및 테스트 구현
  PickPack.xcodeproj/project.pbxproj
  PickPack/App/PickPackApp.swift
  PickPack/Managers/FirestoreManager.swift
  PickPack/Models/Member.swift
  PickPack/Models/SharedItem.swift
  PickPack/Models/User.swift
  PickPack/Views/Room/SharedItem/SharedItemView.swift
  PickPack/Views/TestView/FirebaseLoginTest.swift
  PickPack/Views/TestView/RoomCreateTest.swift
Labels: 🐻앤드류
